### ISSUE TITLE
rom_file='/home/bgoodric/research/python/ale/Arcade-Learning-Environment/roms/pong.bin'

### ISSUE THREAD

**Issue by jxm894** [bbitmaster/pyrlcade#1]
Is your implementation of pyrlcade  includes  "pong.bin" is publicly available?   Thanks!

**Comment by bbitmaster** [comment]
No. I can't provide it here since it is still copyright.

Search google for "pong.bin base64" and in the search results, you may find a base64 encoded version of the rom that you can paste into a text editor, and then convert to the binary file via the "base64 --decode" unix command. You may have to remove space or newline characters.

Alternatively, archive.org contains a large atari 2600 rom collection. You may be able to find it there directly.
